# it is big heading

In [1]:
import numpy as np


In [2]:
list1=list(range(10))
print(list1)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [3]:
list1 = list(range(10))
print(list1)
print(list)
print(type(list1))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>
<class 'list'>


In [4]:
tuple1=tuple(range(5))
print(tuple1)

(0, 1, 2, 3, 4)


In [5]:
x=list(tuple1)
print(x)

[0, 1, 2, 3, 4]


## creating numpy array using list

In [6]:
l1=[10,20,30,40,50]
arr=np.array(l1)
print(arr)
print(type(arr))

[10 20 30 40 50]
<class 'numpy.ndarray'>


In [7]:
#creating a array using tuple
l2=(10,20,30,40,50)
arr1=np.array(l2,dtype=bool)
print(arr1)
print(type(arr))

[ True  True  True  True  True]
<class 'numpy.ndarray'>


## order of datatypes

In [8]:
## order of datatypes

In [9]:
#datatype preference

l2=[10,10.5,10+3j,True,"python"]
arr3=np.array(l2)
print(arr3)

['10' '10.5' '(10+3j)' 'True' 'python']


In [10]:
l2=[10,10.5,10+3j,True]
arr3=np.array(l2)
print(arr3)

[10. +0.j 10.5+0.j 10. +3.j  1. +0.j]


In [11]:
l2=[10,10.5,True]
arr3=np.array(l2)
print(arr3)

[10.  10.5  1. ]


In [12]:
l2=[10,True]
arr3=np.array(l2)
print(arr3)

[10  1]


In [13]:
d1={(10,20,30):"tuple"}
print(d1)

{(10, 20, 30): 'tuple'}


In [14]:
d1={[10,20,30]:"list"}
print(d1)

TypeError: unhashable type: 'list'

In [15]:
s={10,20,30,{40,50}}
print(s)

TypeError: unhashable type: 'set'

In [16]:
x=list(range(1,10))
print(x)

[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [17]:
x2=list(range(1,10,0.5))
print(x2)

TypeError: 'float' object cannot be interpreted as an integer

In [18]:
x3=np.arange(10)
print(x3)

[0 1 2 3 4 5 6 7 8 9]


In [19]:
x4=np.arange(10,20)
print(x4)

[10 11 12 13 14 15 16 17 18 19]


In [20]:
x5=np.arange(1,20,0.5)
print(x5)

[ 1.   1.5  2.   2.5  3.   3.5  4.   4.5  5.   5.5  6.   6.5  7.   7.5
  8.   8.5  9.   9.5 10.  10.5 11.  11.5 12.  12.5 13.  13.5 14.  14.5
 15.  15.5 16.  16.5 17.  17.5 18.  18.5 19.  19.5]


In [21]:
x6=np.arange(1,10,10,dtype=int)
print(x6)

[1]


# arange belongs to numpy library which is used to generate numbers like int or float or etc

In [22]:
y=np.linspace(1,6,10,dtype=int)
print(y)

[1 1 2 2 3 3 4 4 5 6]


## creating 2d arrays using nested list

In [23]:
x=[[10,20,30],[40,50,60]]
arr1=np.array(x)
print(arr1)

[[10 20 30]
 [40 50 60]]


In [26]:
print(len(arr1))

2


In [27]:
print(arr1.ndim)

2


In [28]:
print(arr1.shape)

(2, 3)


In [29]:
print(arr1.size)

6


In [30]:
arr7=np.arange(9).reshape(3,3)
print(arr7)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [32]:
arr8=np.arange(1,13).reshape(3,4)
print(arr8)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [33]:
arr9=np.arange(1,13).reshape(4,3)
print(arr9)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
a=[10,20,30,40]
arr9=np.array(a,ndmin=2)
print(arr9)

[[10 20 30 40]]


In [39]:

arr10=np.array([[10,20],[30,40]])
print(arr10)

[[10 20]
 [30 40]]


In [42]:
print(arr10.flatten())


[10 20 30 40]


In [43]:
## arthmetic expressions

In [44]:
x1=np.arange(1,5).reshape(2,2)
x2=np.arange(1,5).reshape(2,2)
print(x1)
print(x2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [45]:
print(10+5)
print([10]+[5])

15
[10, 5]


In [46]:
print(x1+5)

[[6 7]
 [8 9]]


In [47]:
print(x1+x2)

[[2 4]
 [6 8]]


In [48]:
##accessing the elemnts

In [49]:
arrl1=np.arange(20).reshape(5,4)
print(arrl1)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]]


In [50]:
print(arrl1[0])

[0 1 2 3]


In [51]:
print(arrl1[-1])

[16 17 18 19]


In [52]:
print(arrl1[:,:2])

[[ 0  1]
 [ 4  5]
 [ 8  9]
 [12 13]
 [16 17]]


In [53]:
print(arrl1[0])

[0 1 2 3]


In [54]:
print(arrl1[0])

[0 1 2 3]


In [55]:
print(arrl1[-1])

[16 17 18 19]


In [56]:
print(arrl1[-2])

[12 13 14 15]


In [57]:
print(arrl1[0:2])

[[0 1 2 3]
 [4 5 6 7]]


In [58]:
print(arrl1[::-1])

[[16 17 18 19]
 [12 13 14 15]
 [ 8  9 10 11]
 [ 4  5  6  7]
 [ 0  1  2  3]]


In [59]:
print(arrl1[:,0])

[ 0  4  8 12 16]


In [60]:
print(arrl1[:,0:1])

[[ 0]
 [ 4]
 [ 8]
 [12]
 [16]]


In [61]:
print(arrl1[::-1,::-1])

[[19 18 17 16]
 [15 14 13 12]
 [11 10  9  8]
 [ 7  6  5  4]
 [ 3  2  1  0]]


In [62]:
print(arrl1[:,1])

[ 1  5  9 13 17]


In [63]:
print(arrl1[1,1])

5


In [64]:
print(arrl1[2,1:])

[ 9 10 11]


# matrices 

In [65]:
b1=np.arange(1,5).reshape(2,2)
b2=np.arange(1,5).reshape(2,2)
print(b1)
print(b2)

[[1 2]
 [3 4]]
[[1 2]
 [3 4]]


In [66]:
print(b1*b2)

[[ 1  4]
 [ 9 16]]


In [84]:
res=np.dot(b1,b2)
print(res)

[[ 7 10]
 [15 22]]


In [85]:
b3=np.array([1,2])
b4=np.array([[1],[2]])
res1=np.dot(b3,b4)
print(res1)

[5]


# matrix multiplication rule: number of column in first matrix is equal to number of rows in second matrix

In [86]:
b3=np.array([[1],[2]])
b4=np.array([[1],[2]])
res1=np.dot(b3,b4)
print(res1)

ValueError: shapes (2,1) and (2,1) not aligned: 1 (dim 1) != 2 (dim 0)

## bultin functions to create matrices

In [87]:
n1=np.arange(1,5).reshape(2,2)
print(n1)

[[1 2]
 [3 4]]


In [90]:
n2=np.zeros((2,2))
print(n2)

[[0. 0.]
 [0. 0.]]


In [73]:
n3=np.ones((2,2),dtype=int)
print(n3)

[[1 1]
 [1 1]]


In [74]:
n4=np.full((2,2),5,dtype=int)
print(n4)

[[5 5]
 [5 5]]


In [92]:
n5=np.eye(3,dtype=int)*4
print(n5)

[[4 0 0]
 [0 4 0]
 [0 0 4]]


## aggregate functions

In [95]:
n6=np.random.randint(1,60,10)
print(n6)

[45 48 10 15 37 46  9 29 36  8]


In [77]:
print(np.max(n6))
print(np.min(n6))
print(np.argmax(n6))
print(np.argmin(n6))
print(np.mean(n6))
# print(np.mode(n6))
print(np.median(n6))

52
22
2
1
32.2
33.0


## joining of matrices

In [78]:
m1=np.arange(1,10).reshape(3,3)
m2=np.arange(11,20).reshape(3,3)
print(m1)
print(m2)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]


In [79]:
print(np.concatenate((m1,m2),axis=0))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [80]:
print(np.concatenate((m1,m2),axis=1))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [81]:
print(np.vstack((m1,m2)))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [11 12 13]
 [14 15 16]
 [17 18 19]]


In [82]:
print(np.hstack((m1,m2)))

[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]
 [ 7  8  9 17 18 19]]


In [83]:
c1=np.array([1,2])
c2=np.array([3,4])
print(np.concatenate((c1,c2),axis=0))

[1 2 3 4]
